export const ADD_ITEM_ACTION = 'ADD_ITEM_ACTION';
export const REMOVE_ITEM_ACTION = 'REMOVE_ITEM_ACTION';
export const UPDATE_ITEM_ACTION = 'UPDATE_ITEM_ACTION';
export const UPDATE_ITEM_SUBSTITUTE_ACTION = 'UPDATE_ITEM_SUBSTITUTE_ACTION';
export const CLEAR_CART_ACTION = 'CLEAR_CART_ACTION';
export const SHOPPING_CART = 'SHOPPING_CART';
